// Fresh / aging / stale for a hand-sourced row's check date (the corridor
// page's per-row dates). Its own module so client components can use it
// without bundling lib/corridors.ts and its data file into the browser.
export type Freshness = "fresh" | "aging" | "stale";

// Shared fresh/aging/stale cutoff (7 / 30 days) for any single ISO
// "YYYY-MM-DD" dateChecked -- the one place this threshold is defined.
// The per-provider freshness badges on the compare page (keyed to that row's
// own date) call this rather than hardcoding the cutoffs. There is deliberately
// no whole-corridor version: a homepage caption keyed to a corridor's oldest
// row attributed one provider's staleness (usually hand-sourced PayPal) to
// whichever provider the card named, so it was removed (2026-10-04).
export function freshnessLevelFor(dateChecked: string): Freshness {
  const days =
    (Date.now() - new Date(dateChecked).getTime()) / (1000 * 60 * 60 * 24);
  return days <= 7 ? "fresh" : days <= 30 ? "aging" : "stale";
}

// Tailwind utility class per level, generated by the --color-fresh/aging/
// stale tokens in app/globals.css's @theme inline block. Centralized here
// so every freshness dot renders the same color for the same level instead of
// each component hand-rolling the mapping.
export const FRESHNESS_DOT_CLASS: Record<Freshness, string> = {
  fresh: "bg-fresh",
  aging: "bg-aging",
  stale: "bg-stale",
};
